default: &default
adapter: postgresql
encoding: unicode

pool: 5

development: <<: *default
database: plant-api

test: <<: *default
database: plant-api_test

production: <<: *default
database: plant-api_development
username: plant-api
# password: <%= ENV['PROJECT_NAME_PASSWORD'] %>
